# IDENTIFIER
TT_ID = 'Identifier'

# OPERATORS
TT_ASSIGN = 'Assignment'
TT_PLUS = 'PLUS'
TT_MINUS = 'MINUS'
TT_MUL = 'MUL'
TT_DIV = 'DIV'
TT_INTDIV = 'INTDIV'
TT_EXPO = 'EXPO'
TT_MOD = 'MOD'

# UNARY
TT_INCRE = 'INCREMENT'
TT_DECRE = 'DECREMENT'
TT_POSITIVE = 'POSITIVE'
TT_NEGATIVE = 'NEGATIVE'

# RELATIONAL
TT_GREATER = 'Greater_than'
TT_LESS = 'Less_than'
TT_GREATEREQUAL = 'Greater_Equal'
TT_LESSEQUAL = 'Less_Equal'
TT_EQUALTO = 'Equal_to'
TT_NOTEQUAL = 'Not_Equal'

# LOGICAL
TT_NOT = 'NOT'
TT_AND = 'AND'
TT_OR = 'OR'

# CONSTANTS
TT_INT = 'Number'
TT_FLOAT = 'Decimal'
TT_STR = 'Text'
TT_BOOL = 'Bool'

# DATA TYPES
TT_DTYPE = 'Data_Type'

# KEYWORDS
TT_KWORD = 'Keyword'

# RESERVED WORDS
TT_RWORD = 'Reserved_Word'

# NOISE WORDS
TT_NWORD = 'Noise_Word'

# COMMENTS
TT_COMMENT = 'Comment'

# PUNTUATIONS
TT_COMMA = 'Comma'
TT_SEMICOLON = 'Semicolon'
TT_LSQUARE = 'Left_Square'
TT_RSQUARE = 'Right_Square'
TT_LPAREN = 'Left_Paren'
TT_RPAREN = 'Right_Paren'

# END OF FILE
TT_EOF = 'TT_EOF'